name: Build Manylinux Wheel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build Python Wheels (manylinux_2_36)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Maturin
        run: pip install maturin

      - name: Build manylinux wheel
        working-directory: python
        run: |
          maturin build --release --manylinux 2_36 --interpreter python${{ matrix.python-version }}

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.python-version }}
          path: python/target/wheels/*.whl
